# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

matrix:
  include:
  - env: GHCVER=7.10.3 STACK_YAML=stack-3.22.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.2
  - env: GHCVER=7.10.3 STACK_YAML=stack-4.2.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.3
  - env: GHCVER=7.10.3 STACK_YAML=stack-5.18.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.3
  - env: GHCVER=7.10.3 STACK_YAML=stack-6.18.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.3
  - env: GHCVER=8.0.1
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.0.1

before_install:
  # stack
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  # ghc
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  # hscolour
  - stack install hscolour

install:
  - stack --no-terminal --skip-ghc-check setup
  - stack --no-terminal --skip-ghc-check test --only-snapshot

script:
  - stack --no-terminal --skip-ghc-check test
  - stack --no-terminal --skip-ghc-check haddock
